### ISSUE TITLE
Crashes on .NET standard

### ISSUE THREAD

**Issue by Pilvinen** [xoofx/Tomlyn#11]
`var doc = Toml.Parse(text);`

Makes Tomlyn crash on .NET Standard 2.0 and 2.1. Works fine on .NET Framework.

.NETStandard 2.0 was listed in Frameworks and Dependencies on NuGet, so I'm at least assuming it's supposed to work at least with 2.0.

To my knowledge I didn't do anything special as far as installation issues go, which was my first thought. I simply installed Tomlyn from NuGet. Ran my code. Boom. It's dead.

Switched to .NET framework -> works fine.

Here's my full error:

`ERROR: _update_exports: Exception thrown from constructor of temporary MonoObject:
   At: modules/mono/csharp_script.cpp:2375.

Unhandled Exception:
System.IO.FileNotFoundException: Could not load file or assembly 'Tomlyn, Version=0.1.2.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
File name: 'Tomlyn, Version=0.1.2.0, Culture=neutral, PublicKeyToken=null'
  at Configuration.Config..ctor (System.String configFileName, System.Collections.Specialized.OrderedDictionary defaultValues) [0x0005d] in <c3979e6a132645328736f76311df90b9>:0 
  at Rituals.Configs.Options..ctor () [0x00030] in <3000c4924d3840efa5ea49b53302a895>:0 
ERROR: debug_send_unhandled_exception_error: System.IO.FileNotFoundException: Could not load file or assembly 'Tomlyn, Version=0.1.2.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
   At: modules/mono/mono_gd/gd_mono_utils.cpp:371.`

**Comment by xoofx** [comment]
> Makes Tomlyn crash on .NET Standard 2.0 and 2.1. Works fine on .NET Framework.

There is no such thing as .NET Standard 2.0 runtime, so what do you mean exactly? That the .NET Standard 2.0 DLL of Tomlyn is crashing when using it?

Also I can see the crash in Mono. What Mono version is it? Is it from the command line? How do you know that the Mono runtime you are using is supporting .NET Standard 2.0?

**Comment by Pilvinen** [comment]
.NET Standard in Rider:

![image](https://user-images.githubusercontent.com/4374351/99648643-f1ad7780-2a5b-11eb-83c3-c9a8b89f53f6.png)

Mono log:

https://pastebin.com/RYnyY7p1

Crash:

`Unhandled Exception:
System.TypeInitializationException: The type initializer for 'Rituals.Configs.Options' threw an exception. ---> System.IO.FileNotFoundException: Could not load file or assembly 'Tomlyn, Version=0.1.2.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
  at Configuration.Config..ctor (System.String userDir, System.String configFileName, System.Collections.Generic.Dictionary`2[TKey,TValue] defaultValues) [0x00075] in /home/pilvinen/Godot/Rituals-client/Libraries/Configuration/Sources/Config.cs:29 
  at Rituals.Configs.Options..cctor () [0x00026] in /home/pilvinen/Godot/Rituals-client/Sources/Configs/Options.cs:28 
   --- End of inner exception stack trace ---
`

**Comment by xoofx** [comment]
I can't tell from the context here, it could be anything going wrong in your project, specially with `Could not load file or assembly 'Tomlyn, Version=0.1.2.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies`. I don't know where this library is on your disk, with which Mono do you run it...etc. If you have a simple command line repro with mono and a simple exe that would prove this. FWIW Tomlyn is working fine with netstandard2.0 in the CI, so it is likely an invalid setup on your side.

**Comment by Pilvinen** [comment]
In that case it's probably an issue with Rider or Godot, because the only thing I did was install Tomlyn from NuGet through Rider's graphical interface. Nothing fancy going on in the project.

Or maybe it's Linux specific issue.

**Comment by xoofx** [comment]
Just tried 

```csharp
using System;
using Tomlyn;

namespace TestTomlyn
{
    class Program
    {
        static void Main(string[] args)
        {
            var toml = Toml.Parse("[test]\na = 1\nb = 2");
            
            Console.WriteLine($"Hello World! {toml}");
        }
    }
}
```

with a net472 and netcoreapp2.1 console app. 

If I run the net472, force to make sure that the netstandard2.0 is used and run it with mono:

```
> "C:\Program Files\Mono\bin\mono.exe" TestTomlyn.exe
﻿﻿Hello World! [test]
a = 1
b = 2
```

So it sounds more likely an issue with godot mono embedded runtime or similar.

**Comment by Pilvinen** [comment]
I also tried reproducing the issue just now in vanilla C# in .NET core console project that uses a .NET standard 2.1 library.

And I wasn't able to reproduce the issue, it worked perfectly. Unfortunately I'm also unable to find the cause of the error when using Godot and the aforementioned setup.

I guess I will stick to .NET Framework for now. Thank you for confirming that it's not an issue in Tomlyn.
