### ISSUE TITLE
Error Installing the package

### ISSUE THREAD

**Issue by litch0** [xoofx/Tomlyn#14]
I get this error every time I tried to install the package 
```Shell
info :   Valid from: 4/9/2018 9:00:00 PM to 4/14/2021 9:00:00 AM
error: NU3037: Package 'Tomlyn 0.1.2' from source 'https://api.nuget.org/v3/index.json': The repository primary signature validity period has expired.
```

**Comment by xoofx** [comment]
It was a problem with NuGet - not related to Tomlyn. See this [issue](https://github.com/NuGet/Announcements/issues/49)

**Comment by litch0** [comment]
Ok, I just tried installing and it is working now, sorry for the unnecessary issue.
