### ISSUE TITLE
Add arbitrary SyntaxNode to TableSyntax?

### ISSUE THREAD

**Issue by chucker** [xoofx/Tomlyn#15]
I want to produce TOML that looks roughly like this:

```
[SomeCategory]
"Some string key" = "Some string"
"Some array key" = [ 0, 1, 2, 3 ]
"Some table key" =
[
    {
        "Some key" = "Some value"
    }
]
````

That is, I have a table, and its keys can in turn not just contain values, but also arrays and nested tables.

To that end, I have a bunch of classes that implement a common interface method which returns the abstract `SyntaxNode` class. Depending on the class, this is either `ArraySyntax`, `StringValueSyntax`, or `TableSyntax`.

That method's returned `SyntaxNode` is then supposed to be added to a (parent) `TableSyntax`.

A design like this _seemed_ to work with [a different library](https://github.com/dezhidki/Tommy), which I'm trying to replace with this one due to unpredictable whitespace behavior. However, it doesn't seem like I can add most node types to a `TableSyntax` — there's an `Add` overload on the `Items` collection that takes a `KeyValueSyntax`, but that in turns only takes certain value types.

Are nested tables supported at all? Am I going about this wrong?

**Comment by xoofx** [comment]
Can't tell what you are doing without seeing how you construct the code, but that should be supported. Instead, parse the TOML above and see how is structured the syntax tree, you should be able to figure out what is missing.

**Comment by chucker** [comment]
> Instead, parse the TOML above and see how is structured the syntax tree, you should be able to figure out what is missing.

Oh, good point! That even gives me validation errors. Thanks.
