### ISSUE TITLE
Comments are not kept in the syntax tree

### ISSUE THREAD

**Issue by madskristensen** [xoofx/Tomlyn#17]
When building the VS editor for .toml files, I have no way to colorize comments because they are stripped out of the syntax tree. Please consider keeping them in, so I a full colorization/classification is possible.

**Comment by xoofx** [comment]
They are not stripped out but stored in SyntaxTrivia (leading/trailing), but the nodes on which they are attached are not always obvious (sometimes it is after e.g EndOfLineToken for example)

How are you using syntax coloring? Do you provide e.g intellisense (So you need more contextual knowledge via the syntax tree) or just token highlighting would be enough?

I'm improving the lot the library these days, so I could easily add a `Toml.Tokenize` method for example, if you just needs basic syntax hightlighting.

**Comment by madskristensen** [comment]
I'm not doing IntelliSense, so just basic syntax highlighting. I'll take a look at the trivia properties. thanks

**Comment by xoofx** [comment]
hey, I have added support for querying tokens. This is described in the documentation [here](https://github.com/xoofx/Tomlyn/blob/main/doc/readme.md#32-fetching-tokens-from-a-toml-string)

**Comment by madskristensen** [comment]
Awesome. Thank you so much!!!
