### ISSUE TITLE
Add version property like Markdig

### ISSUE THREAD

**Issue by madskristensen** [xoofx/Tomlyn#18]
I'd love to show what version of Tomlyn the VS editor extension is using, like the Markdown extension does for Markdig. There currently is no property in Tomlyn showing its version number, like Markdig has.

**Comment by xoofx** [comment]
Yep, I will add this later today.

**Comment by xoofx** [comment]
Fixed in Tomlyn >= `0.9.0`

The `Toml.Version` returns a string of the Tomlyn version.
