### ISSUE TITLE
C# nullable support is sketchy

### ISSUE THREAD

**Issue by mpdetwiler** [xoofx/Tomlyn#24]
- I have installed 0.11.0 from nuget, I used to use an older version
- In this new (newest?) version now the operator[] for TomlTable return "object?" instead of just "object"
- I was under the impression that this never returns null because it will throw KeyNotFoundException instead
- So now I have to put a ! after every TomlTable lookup ie (long)myTable["some-integer"]!
- I've had to put literally hundreds of ! to update my codebase to nullable
- It is bad practice to use so much null forgiveness especially when the function doesn't actually return null (as far as I know)

WHY did you change the return type from "object" to "object?" (did you?) should have just left it alone. Change it back pretty please?

**Comment by xoofx** [comment]
> WHY did you change the return type from "object" to "object?" (did you?) should have just left it alone. Change it back pretty please?

It was an oversight. As I'm no longer using `TomlTable` directly and I didn't check the usage experience. I will change it back.

**Comment by mpdetwiler** [comment]
> It was an oversight. As I'm no longer using `TomlTable` directly and I didn't check the usage experience. I will change it back.

Okay well I just realized something. Does or has the library always (even before 0.4.0) allowed users to SET keys to map to null objects? If that is the case then the GET could return null if the user ever set it to null for a particular key. In that case I don't think you could change it back because some users might have abused that. I never set keys in my codebase so I never thought of that.

**Comment by xoofx** [comment]
> WHY did you change the return type from "object" to "object?" (did you?) should have just left it alone. Change it back pretty please?

Oh, and also, in the future, when you start to interact with a project owner that has dedicated its time to make it available for free, you could start your message with "Hey, I'm using your library and it's really helpful, thank you.".

**Comment by mpdetwiler** [comment]
> > WHY did you change the return type from "object" to "object?" (did you?) should have just left it alone. Change it back pretty please?
> 
> Oh, and also, in the future, when you start to interact with a project owner that has dedicated his time to make it available for free, you could start your message with "Hey, I'm using your library and it's really helpful, thank you.".

I apologize. Do you have cash app or venmo or something?

**Comment by xoofx** [comment]
This should be fixed in 909dd77 and will be available in next version
