### ISSUE TITLE
IsSafeStringLiteralMulti returning false for windows (CRLF) newlines

### ISSUE THREAD

**Issue by nyctef** [xoofx/Tomlyn#25]
Hi! I've been investigating this library to see if we could use it and it looks pretty cool so far - thanks!

I think I might have found a bug, though. I'm trying to use `TomlPropertyDisplayKind.StringLiteralMulti` but it's not working as expected. I thing the issue might be in this line:

https://github.com/xoofx/Tomlyn/blob/477d57398b76c371514729201b8c5ff800c723e4/src/Tomlyn/Helpers/TomlFormatHelper.cs#L230

there's a `'n'` that's probably supposed to be a `'\n'`.

**Comment by xoofx** [comment]
Likely, PR welcome
