### ISSUE TITLE
In unity InvalidCastException: Specified cast is not valid.

### ISSUE THREAD

**Issue by YanYeek** [xoofx/Tomlyn#27]
![image](https://user-images.githubusercontent.com/48875922/156680727-70fd88bd-e99c-4dd3-a637-cae474fd59ad.png)
Tomlyn version Tomlyn.0.12.0 netstandard2.0
Unity version 2020.3.23f1c1 
![image](https://user-images.githubusercontent.com/48875922/156681146-84a7a94a-0596-4b2a-ab8f-a53ce140c848.png)
I don't know why!

**Comment by xoofx** [comment]
Similar to #23
It seems that it is incompatible in Unity (while I tested it with plain mono), I will investigate.

**Comment by xoofx** [comment]
Should be fixed by commit 21de2ab and available soon in `0.12.1+`
