### ISSUE TITLE
Toml.TryToModel not calling ConvertTo option

### ISSUE THREAD

**Issue by donaldblodgett** [xoofx/Tomlyn#30]
I am attempting to use Tomlyn to read/write a model that contains properties that are non-primitive. Given the following code I would expect that the resulting model would contain the Uri as parsed from the sample text as the TomlModelOptions.ConvertTo is defined. Instead the test fails with the diagnostics containing the following error:

`The property value of type System.String couldn't be converted to System.Uri for the property Tests+Config/service_uri`

```C#
    [Test]
    public void TestUri()
    {
        var expected = new Uri("https://example.com");
        var text = @$"service_uri = ""{expected}""";
        var options = new TomlModelOptions
        {
            ConvertTo = (value, type) => new Uri((string)value)
        };
        var success = Toml.TryToModel<Config>(text, out var result, out var diagnostics, null, options);
        
        Assert.True(success);
        Assert.AreEqual(expected, result?.ServiceUri);
    }

    public class Config
    {
        public Uri ServiceUri { get; set; }
    }
```

Through debugging this issue it seems that if I temporarily change the value of the variable `value` at the following line to null

https://github.com/xoofx/Tomlyn/blob/9d99bb3228d72a3a1098d27fa198b72730561f5c/src/Tomlyn/Model/Accessors/DynamicModelReadContext.cs#L92

and then revert it back to the original value at the following line

https://github.com/xoofx/Tomlyn/blob/9d99bb3228d72a3a1098d27fa198b72730561f5c/src/Tomlyn/Model/Accessors/DynamicModelReadContext.cs#L164

then the `ConvertTo` option is successfully called and the test passes.

**Comment by xoofx** [comment]
This is fixed by commit 9b0e19e

https://github.com/xoofx/Tomlyn/blob/9b0e19ebc6d03870f7509f619c5d0e524e4a6fab/src/Tomlyn.Tests/ModelTests/ReflectionModelTests.cs#L31-L48

There are now 2 properties:

- `TomlModelOptions.ConvertToModel` (previously `ConvertTo`).
- `TomlModelOptions.ConvertToToml` to allow to convert back a custom type to a TOML representation.

Should be available in `0.14.0+`
