### ISSUE TITLE
Retaining same style when exporting a previously-imported custom model?

### ISSUE THREAD

**Issue by sdarkwell** [xoofx/Tomlyn#32]
Hello,

Firstly, thank you for creating and maintaining such a fantastic project! It is truly appreciated. :)

I am struggling to have Tomlyn preserve the original style of a TOML document, even when using the ITomlMetadataProvider. Example:

```
public class ParentModel : ITomlMetadataProvider {
    public Dictionary<string, ChildModel> children { get; set; } = new();
    TomlPropertiesMetadata? ITomlMetadataProvider.PropertiesMetadata { get; set; }
}

public class ChildModel : ITomlMetadataProvider {
    public int number { get; set; }
    TomlPropertiesMetadata? ITomlMetadataProvider.PropertiesMetadata { get; set; }
}

internal class Program {
    private const string raw = @"children.first.number = 1
children.second.number = 2
children.third.number = 3";   
    
    static void Main(string[] args) {
        var model = Toml.ToModel<ParentModel>(raw);
        var toml = Toml.FromModel(model);
        Console.WriteLine(toml);
    }
}
```

The expected output would be the same as the input:
> children.first.number = 1
> children.second.number = 2
> children.third.number = 3

Instead, I receive the following output:
> [children.first]
> number = 1
> [children.second]
> number = 2
> [children.third]
> number = 3

Additionally, strings including back-slashes that are originally enclosed within single quotes are converted into strings contained by quotation marks with backslashes replaced with double-backslashes.

My particular usecase is for editing .toml config files generated by Minecraft Forge mods; these files may later be reviewed by other users outside of the application, so keeping the original formatting close to the original is important.

Any assistance with this is greatly appreciated. :)

**Thank you and be well!**
\- S.

**Comment by xoofx** [comment]
> The expected output would be the same as the input:

This is not something to expect from the model. 😉 

`ITomlMetadataProvider` provides basic support for keeping comments around but nothing more. If you want to have a strict equivalence, you can't use the model but need to interact with the syntax tree instead (the result of the parse method). Interacting with the syntax tree is less convenient to use, but it provides exact representation (keep spaces, exact order of declaration...etc.)

**Comment by sdarkwell** [comment]
**Hello @xoofx,**

Thank you for the response, and the guidance!

That absolutely makes sense, and I will proceed with that track. :)

**Thank you so much, and be well!**
\- S.
