### ISSUE TITLE
Installing

### ISSUE THREAD

**Issue by nchistov** [xoofx/Tomlyn#52]
Hello.

Why the installing topic isn't in README file? I found [this](https://www.nuget.org/packages/Tomlyn) page. I can install Tomlyn for my c# project by using this command:

```
$ dotnet add package Tomlyn --version 0.16.2
```

But no link on that page or this command isn't in README.

PS: That command must entered in folder of c# project. For example:

```
$ cd <folder of c# project>
$ dotnet add package Tomlyn --version 0.16.2
```

I'll hope you add `Installing` topic to README.

**Comment by xoofx** [comment]
Indeed, fixed by a4faf8c
