### ISSUE TITLE
Unable to mix inline and non-inline array of tables

### ISSUE THREAD

**Issue by regalialong** [xoofx/Tomlyn#74]
Hey, I've stumbled onto this in my code and made this reproduction code:
```cs
using Tomlyn;

const string testString = """
                          [[objects]]
                          [[objects.nest2list]]
                          data = "test1"
                          [[objects.nest2list]]
                          data = "test2"

                          [[objects]]
                          nest2list = [{ data = "test3" }]
                          """;
var parseResult = Toml.ToModel<Test1>(testString);
Console.WriteLine(parseResult.Objects![0].nest2list![0].data);
public class Test1
{
    public List<Nest1>? Objects { get; set; }
}

public class Nest1
{
    public List<Nest2>? nest2list { get; set; }
}

public class Nest2
{
    public required string data { get; set; }
}
```

Running this code however returns me:
```
Unhandled exception. Tomlyn.TomlException: (8,1) : error : The key `objects.[1].nest2list` is already defined at (2,1) with `[[objects.nest2list]]␤data = "test1"` and cannot be redefined
(8,16) : error : The key `objects.[1].nest2list.[1].data` is already defined at (5,1) with `data = "test2"` and cannot be redefined
```

https://www.toml-lint.com thinks the TOML is valid and https://pseitz.github.io/toml-to-json-online-converter is able to correctly parse this TOML into its JSON equivalent:
```json
{
  "objects": [
    {
      "nest2list": [
        {
          "data": "test1"
        },
        {
          "data": "test2"
        }
      ]
    },
    {
      "nest2list": [
        {
          "data": "test3"
        }
      ]
    }
  ]
}
```
If I remove the inline declaration (test3), the code works again and if I replace it with its non-inline equivalent, it works as well.

Is this a bug? Am I missing something? It's not an issue for the reproduction code but it's desirable in my code at times to declare a table inline because it's more concise.

**Comment by xoofx** [comment]
I believe that as per the [spec](https://toml.io/en/v1.0.0#array-of-tables), this is not possible:

> Attempting to define a normal table with the same name as an already established array must produce an error at parse time. Attempting to redefine a normal table as an array must likewise produce a parse-time error.

`nest2list` is initially a table array, but `test3` tries to make it a normal table.

**Comment by regalialong** [comment]
Oh, that's unfortunate. That other tooling doesn't seem to mind this is incredibly odd, but I don't believe this is a major blocker for me so I'll close this.

Thanks for the clarification!

**Comment by xoofx** [comment]
I'm not entirely 100% sure though, might require to use an official parser/linter (dunno if there are any actually), or to raise the issue at https://github.com/toml-lang/toml for clarification.
