### ISSUE TITLE
Suggest adding PolySharp

### ISSUE THREAD

**Issue by lilith** [xoofx/Tomlyn#79]
I've recently migrated most of my nuget packages / oss projects to using PolySharp - I can set language=latest and still target .NET Standard 2.0 - it's great. 
It's particularly essential for .NET 8 features, such as annotating for trimming/etc.

In Tomlyn.props, add
```
<PolySharpIncludeRuntimeSupportedAttributes>true</PolySharpIncludeRuntimeSupportedAttributes>
```
And 

```
    <!--Polyfill language features for .NET Standard 2.0 et all, generating internal
        items only for the compiler. Enables langversion=latest-->
    <PackageReference Include="PolySharp" Version="1.*">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
```

The only issue I've had with the library is that since it generates internal stuff, InternalsVisibleTo can cause duplications if there is both a mismatch on targeted frameworks and the consuming (typically unit test) project also includes it unnecessarily. Easily avoided, though.

**Comment by xoofx** [comment]
> I've recently migrated most of my nuget packages / oss projects to using PolySharp - I can set language=latest and still target .NET Standard 2.0 - it's great.

Agreed. Feel free to open a PR.

**Comment by lilith** [comment]
I can do that. Could you merge or review my current one?

**Comment by xoofx** [comment]
> I can do that. Could you merge or review my current one?

Oops, sorry, I retriggered the pipeline but forgot to come back to check and merge, done! 😅

**Comment by lilith** [comment]
https://github.com/xoofx/Tomlyn/pull/81
