### ISSUE TITLE
Add .NET 8 target 

### ISSUE THREAD

**Issue by lilith** [xoofx/Tomlyn#82]
Suggesting adding a .NET 8 target to the core and test projects and to CI. 

We could also consider adding an ubuntu-latest test to the matrix? It's not like the library does much OS integration, but OS pivots are common in the ecosystem and some future day it might be helpful. ubuntu might also complete faster.

Other considerations: [.NET 7 EOL is May 14, 2024](https://dotnet.microsoft.com/en-us/platform/support/policy/dotnet-core)

We have a few .NET 6 ifdefs with additional DateOnly etc type support, and .NET 6 isn't EOL until Nov 12. 
Perhaps the targets should be .NET 6 & 8 to avoid breaking that type for .NET 7 users?

**Comment by lilith** [comment]
I've added this to #79. I noticed that the library was not being tested against any .NET Standard 2.0 platform, so I added a conditional net48 target for the unit tests and added ubuntu to the ci matrix

**Comment by lilith** [comment]
The CI is now working for me on my fork, so it should be ready to merge if this is the directly you want to go (6+8+.Net Standard 2), test (ubuntu + windows) x (6, 8, net48)

**Comment by xoofx** [comment]
Fixed by #81 

> Perhaps the targets should be .NET 6 & 8 to avoid breaking that type for .NET 7 users?
> The CI is now working for me on my fork, so it should be ready to merge if this is the directly you want to go (6+8+.Net Standard 2), test (ubuntu + windows) x (6, 8, net48)

Yeah, let's try net6.0 and net8.0 and see how it goes. Don't have a strong opinion on it.
