### ISSUE TITLE
Add support for TOML 1.0.0

### ISSUE THREAD

**Issue by xoofx** [xoofx/Tomlyn#9]
New [TOML specs](https://github.com/toml-lang/toml/blob/master/toml.md) are in the work, it will probably require to add more tests and check that Tomlyn is actually following it.

**Comment by markusr** [comment]
Any updates on this?

**Comment by xoofx** [comment]
> Any updates on this?

No personal time these days allocated to this issue.

**Comment by arphox** [comment]
The issue should probably be renamed to "Add support for TOML 1.0.0" since [1.0.0's full spec](https://toml.io/en/v1.0.0) is done now.

**Comment by mwasplund** [comment]
One major change that needs to be supported is the ability to have mixed types in arrays.

**Comment by xoofx** [comment]
Fixed by dacad96
