### ISSUE TITLE
Newlines in inline tables

### ISSUE THREAD

**Issue by dwilliamson** [xoofx/Tomlyn#91]
Is there any chance of supporting newlines in inline tables?

It appears this was added to the spec in 2022: https://github.com/toml-lang/toml/issues/516

It looks to be something as simple as allowing newlines to be eaten in this piece of code here, which contains explicit logic to error when newlines are encountered: https://github.com/xoofx/Tomlyn/blob/c264d1d7a417a51e9e8aec04b867be7248d3200a/src/Tomlyn/Parsing/Parser.cs#L374

**Comment by xoofx** [comment]
Fixed by b2377a1

**Comment by dwilliamson** [comment]
Thank you for the quick response!
